### ISSUE TITLE
could you make scrollbar on the right hidden as it's a bit distracting when watching videos and a video web page is not that long to need it.  [youtube classic]

### ISSUE THREAD

**Issue by mhwgoo** [adamlui/userscripts#106]
My browser has this feature, but this script overrides it, thanks!

**Comment by adamlui** [comment]
Can you disable the script, then screenshot what you mean?

**Comment by mhwgoo** [comment]
Sorry I may have misjudged at midnight yesterday. It is my browser's little quirk, not your userscript. The scenario is that when the youtube webpage is refreshed, all prior configs and this youtube classic userscript got lost. Like this:
- before refreshement:
![Uploading Screenshot 2024-10-26 at 10.52.42.png…]()

-after refreshment:
![Uploading Screenshot 2024-10-26 at 10.53.09.png…]()

**Comment by adamlui** [comment]
Hey @mhwgoo when I refresh it stays square, what browser and userscript manager are you using?

Also do you think it should hide Shorts?

**Comment by mhwgoo** [comment]
I've been using qutebrowser recently, and I put your script under `$HOME//.qutebrowser/greasemonkey` folder as the official docs indicate. 

I dont' know about others, but I never watch Shorts, and I'd like it to be hidden.

BTW, it'd be great if ad nodes could be deleted and not rendered (instead of hidden), I tried to delete the first ad node by `document.getElementsByTagName("ytd-ad-slot-renderer")[0].parentNode.parentNode.remove();` in `dev-tools` and it worked but it didn't work on actual web after I added this line in your script. Do you know why? Could you add this feature?

**Comment by mhwgoo** [comment]
It looks like it works when there is this css style:
```css
ytd-ad-slot-renderer {
  display: none;
}
```

**Comment by adamlui** [comment]
Thanks for the info @mhwgoo I updated userscript so Shorts sections are now hidden

Re: qutebrowser refresh bug, I downloaded the Windows installer from https://github.com/qutebrowser/qutebrowser/releases but BitDefender alerted me to malware...

![image](https://github.com/user-attachments/assets/77b3c6c3-f413-4472-bbf5-21d999acbdf2)

...so I'm not comfortable testing it unfortunately




> It looks like it works when there is this css style:
> 
> ```css
> ytd-ad-slot-renderer {
>   display: none;
> }
> ```

Do you wanna be a contributor by adding it to the CSS?

**Comment by mhwgoo** [comment]
```css
ytd-ad-slot-renderer {
  display: none;
}
```
This only hides the node with a black block still there. But with this portion of css, the following javascript achieves my intention of making ads disappear:
```javascript
window.addEventListener('animationstart', function() {
    'use strict';

    var ads = document.getElementsByTagName("ytd-ad-slot-renderer");
    for (var i = 0; i < ads.length; i++) {
        ads[i].parentNode.parentNode.remove();
    }
});
```
I'm not sure it's the right way from your expert opinion, afterall I never write javascript and css codes before.

**Comment by adamlui** [comment]
Ok I understand now, for the removal the shortest command is:

```js
document.querySelectorAll('ytd-ad-slot-renderer').forEach(ad => ad.parentNode.parentNode.remove())
```

... and are you saying, when you added the remover using event listener, sometimes it removed, sometimes it did not, but when you also add teh CSS, it always removed? (if so that is quite strange since CSS does not affect whether listener timing was correct so would still show the black boxes)

**Comment by adamlui** [comment]
NVM I understand what you're saying, "with this portion of css" you meant the selector in the remover, but still it doesn't always remove. Let me figure out the best way brb

**Comment by mhwgoo** [comment]
Yeah, you got what I meant. Together "with this portion of css", the above javascript makes the whole youtube web page appear about right (deleted the ad nodes and thus not displaying them). Thanks for your help:)

**Comment by adamlui** [comment]
Ok I figured it out, it kept re-adding so a mutation observer is the best solution, can you update to the latest version 2024.10.28.3 and test it out in qutebrowser

**Comment by adamlui** [comment]
One thing I noticed, now when scrolling and lazy loading finishes, new ads are re-added but instantly removed, so the grid of videos compresses to fill in blank space and all the thumbnails move.

Before when hiding only, this phenomenon does not occur, but there are ugly gaps. Which way is worse? Also what do you think about an option to hide or remove so user picks their poison?

**Comment by adamlui** [comment]
Actually I just tested without the script, YouTube already jars the user by scrolling up instead of staying in place, so I think they will be used to this disorientation already and your ad removal idea is best

**Comment by adamlui** [comment]
Also check this out

![image](https://github.com/user-attachments/assets/71505d61-e589-4e7a-9649-3ec6bc09badb)

Removal results in ugly gaps at ends of some rows for me

**Comment by adamlui** [comment]
NVM jsut fixed it also the grid no longer rearranges either

**Comment by mhwgoo** [comment]
After my last comment, I found youtube is so gross that it keeps refreshes itself with news ads. Just when I was figuring it out, your message came. Just in time. I will test it after dinner. Thanks!

**Comment by mhwgoo** [comment]
Hi @adamlui, I tested the latest version, and it seemed that the page didn't appear as intended. It had this same appearance as soon as the page was first rendered, scrolled down and scrolled back up. Youtube's patterned ad spots were still there.
![Screenshot 2024-10-28 at 22 05 32](https://github.com/user-attachments/assets/1abcdb50-809d-4410-9a01-524abf18f0c2)

**Comment by mhwgoo** [comment]
I did a little thought experiment earlier today with the probably non-idiomatic js code below in a standalone userscript together with a global `stylesheet.css`. The page appeared a bit better when first loaded, scrolled down and back up (with occasional transient `display:none` blocks though).
```javascript
var ads = document.getElementsByTagName("ytd-ad-slot-renderer");

window.addEventListener('animationstart', function() {
    if (ads) {
        for (var i = 0; i < ads.length; i++ ) {
            ads[i].parentNode.parentNode.remove();
        }
    }
    ads = document.getElementsByTagName("ytd-ad-slot-renderer");
});

window.addEventListener('animationend', function() {
    if (ads) {
        for (var i = 0; i < ads.length; i++ ) {
            ads[i].parentNode.parentNode.remove();
        }
    }
    ads = document.getElementsByTagName("ytd-ad-slot-renderer");
});

window.addEventListener('load', function() {
    if (ads) {
        for (var i = 0; i < ads.length; i++ ) {
            ads[i].parentNode.parentNode.remove();
        }
    }
    ads = document.getElementsByTagName("ytd-ad-slot-renderer");
});
```

**Comment by mhwgoo** [comment]
In fact I had been using Brave browser until a few days ago. Brave did some awesome special treatments with yt, making it look like there were no ad at all in all pages as well as within each video. Don't know how Brave achieves that. So I couldn't image yt has become like this. If it wanted to counter ad blocks, it'd better take on some big players like Brave Browser first.

**Comment by adamlui** [comment]
Actually Google triggered a ton of users to switch to Brave after the banning alert. But I will fix it to work in qutebrowser but tomorrow because I was up all night doing something so I have to sleep all day now

**Comment by adamlui** [comment]
Ironically Brave originally lured users using crypto as reward for their push ads (and it still spams you but the pay is pennies compared to the golden days)

**Comment by adamlui** [comment]
They rebranded as AI browser now because of me though

**Comment by adamlui** [comment]
I think I know how to fix, your SS shows the native YouTube logo instead of my custom one, so the timing is off or there are errors in your console

**Comment by mhwgoo** [comment]
That may explain it. Just take your time and have a good rest:)

**Comment by mhwgoo** [comment]
What i hate about brave is it's too bloated, also ridden with crypto stuff. Just no perfect browser on earth.

**Comment by adamlui** [comment]
I was eating then had to wait for digestion before sleep or else acid travels up the stomach and damages the entrance, so I made another update to also remove shelves, can you test what it looks like now, also if console showed error also paste it and tomorrow I will refine it

**Comment by mhwgoo** [comment]
Was asleep. After update, it looked fine at first sight and then quite ok for most time, but still had blank blocks staying for about a few minutes (maybe because of my slow web connection with days old vpn nodes). I'm not sure what you mean by shelves, I assumed the right sidebar when a video is playing? I uploaded some screenshots and a log file.
![Screenshot 2024-10-29 at 09 54 41](https://github.com/user-attachments/assets/0d28e4b0-2981-45bf-9895-9cef4cb3a1e3)
![Screenshot 2024-10-29 at 09 55 45](https://github.com/user-attachments/assets/08a5147d-33a0-4f9f-8c35-e6af26a22b28)
![Screenshot 2024-10-29 at 09 59 08](https://github.com/user-attachments/assets/1b2572e4-2185-4e22-81b6-86f039161423)
[log.zip](https://github.com/user-attachments/files/17550805/log.zip)

**Comment by adamlui** [comment]
Can you change line 27 from

```js
(() => {
```

to

```js
(async () => {
```

then at end of script, below

```js
    // Remove homepage ads/rich sections
    if (location.pathname == '/')
```

add

```js
        await waitForElm('html')
```

so the final routine is

```js
    // Remove homepage ads/rich sections
    if (location.pathname == '/')
        await waitForElm('html')
        new MutationObserver(() => {
            const adSlot = document.querySelector('ytd-ad-slot-renderer'),
                  richSection = document.querySelector('ytd-rich-section-renderer')
            if (adSlot) adSlot.closest('[rendered-from-rich-grid]')?.remove()
            else if (richSection) richSection.remove()
        }).observe(document.documentElement, { childList: true, subtree: true })
```

then can you re-paste the top error block

![image](https://github.com/user-attachments/assets/8356b0f7-4d5b-47da-a7c4-5e582890ee98)

and do the 'Failed to execute 'observe' still appear, also gaps in the thumbnails

**Comment by mhwgoo** [comment]
I can do it later. I'm in the subway right now 😄

**Comment by adamlui** [comment]
oh can you posta picture i want to see China today

**Comment by mhwgoo** [comment]
Sure can! 😂 when I get out of the subway.

**Comment by mhwgoo** [comment]
China right now.
![image](https://github.com/user-attachments/assets/dba2b82d-7b28-4306-9886-a920e2be4c2d)![image](https://github.com/user-attachments/assets/8584da5b-3905-4158-8de5-ac776b1aae85)

**Comment by mhwgoo** [comment]
Seemed even worse now after adding async, await code
![Screenshot 2024-10-29 at 18 58 03](https://github.com/user-attachments/assets/3e2dd85e-0852-44b9-8729-24c190f4930e)

**Comment by adamlui** [comment]
ok can reset by replacing script with the latest version, and then Ctrl+F for `document-start` and replace w/ `document-end` and does the observer error still occur

**Comment by mhwgoo** [comment]
Everything looked just perfect (no observer error, no blank boxes), until a new tab was opened and go to youtube.com.

Tab one:
![Screenshot 2024-10-30 at 13 42 52](https://github.com/user-attachments/assets/5291a458-016d-48f9-9fbe-14ac1aa15384)

Tab two:
![Screenshot 2024-10-30 at 13 43 15](https://github.com/user-attachments/assets/18cdbbc8-f5e2-4709-b33c-e71036904cc0)

**Comment by adamlui** [comment]
ok can you install the latest version is there still observer error

**Comment by adamlui** [comment]
Tab two doesn't show the custom logo so script didn't load for some reason...

**Comment by mhwgoo** [comment]
I got:
```
YouTube™ Classic 📺 — (Remove rounded design + Return YouTube dislikes) called unimplemented GM_registerMenuCommand
userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):1692 Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):1692:24
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):1693:7
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):2208:3
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):2213:3
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):1692
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):1693
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2208
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2213
userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):449 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):449:16
    at new Promise (<anonymous>)
    at waitForElem (userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):445:16)
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):477:5
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):2208:3
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):2213:3
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):449
waitForElem @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):445
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):477
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2208
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2213
Promise.then (async)
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):477
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2208
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2213
userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):449 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):449:16
    at new Promise (<anonymous>)
    at waitForElem (userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):445:16)
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):478:5
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):2208:3
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):2213:3
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):449
waitForElem @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):445
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):478
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2208
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2213
Promise.then (async)
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):478
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2208
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2213
userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):449 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):449:16
    at new Promise (<anonymous>)
    at waitForElem (userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):445:16)
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):1677:5
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):2208:3
    at userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (/Remove rounded design + Return YouTube dislikes):2213:3
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):449
waitForElem @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):445
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):1677
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2208
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2213
Promise.then (async)
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):1677
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2208
(anonymous) @ userscript:GM-https://github.com/adamlui/YouTube%E2%84%A2 Classic %F0%9F%93%BA %E2%80%94 (Remove rounded design + Return YouTube dislikes):2213
```

**Comment by adamlui** [comment]
Actually screenshot is more readable, but can you change the latest version document-start to document-end again, and if new tab doesn't load logo screenshot console

**Comment by mhwgoo** [comment]
Changed back to document-end, it seemed the userscript did not get called.

![Screenshot 2024-10-30 at 20 39 11](https://github.com/user-attachments/assets/e6bad5d0-9302-4f95-8455-e49366e8f9ad)

**Comment by adamlui** [comment]
What about when you refresh second tab? Also you could try installing another userscript, then open new tab and see if phenomenon occurs (if so this is qutebrowser bug worthy of reporting to him)

**Comment by mhwgoo** [comment]
My code:
```javascript
console.log("this is kate")

var ads = document.getElementsByTagName("ytd-ad-slot-renderer");

window.addEventListener('animationstart', function() {
    if (ads) {
        for (var i = 0; i < ads.length; i++ ) {
            ads[i].parentNode.parentNode.remove();
        }
    }

    console.log("animationstart done")
    ads = document.getElementsByTagName("ytd-ad-slot-renderer");
});

window.addEventListener('animationend', function() {
    if (ads) {
        for (var i = 0; i < ads.length; i++ ) {
            ads[i].parentNode.parentNode.remove();
        }
    }

    console.log("animationend done")
    ads = document.getElementsByTagName("ytd-ad-slot-renderer");
});

window.addEventListener('load', function() {
    if (ads) {
        for (var i = 0; i < ads.length; i++ ) {
            ads[i].parentNode.parentNode.remove();
        }
    }

    console.log("load done")
    ads = document.getElementsByTagName("ytd-ad-slot-renderer");
});
```

Screenshot, the script was called and log message printed:
![Screenshot 2024-10-30 at 21 52 29](https://github.com/user-attachments/assets/f5133a92-ed21-41ff-a151-9e68bc8d6799)

**Comment by adamlui** [comment]
Does it happen with document-end vs. document-start

**Comment by mhwgoo** [comment]
I reused your greasemonkey starting syntax, and changed to document-start:
```javascript
// ==UserScript==
// @name          YouTube™ Classic 📺 — (Remove rounded design + Return YouTube dislikes)
// @version       2024.10.30.3
// @author        Adam Lui, Magma_Craft, Anarios, JRWR, Fuim & hoothin
// @namespace     https://github.com/adamlui
// @description   Reverts YouTube to its classic design (before all the rounded corners & hidden dislikes) + redirects YouTube Shorts
// @license       MIT
// @icon          https://media.ytclassic.com/images/icon48.png
// @icon64        https://media.ytclassic.com/images/icon64.png
// @compatible    chrome
// @compatible    firefox
// @compatible    opera
// @compatible    safari
// @compatible    edge
// @match         *://*.youtube.com/*
// @grant         GM_registerMenuCommand
// @grant         GM_unregisterMenuCommand
// @grant         GM_getValue
// @grant         GM_setValue
// @run-at        document-start
// @downloadURL   https://update.greasyfork.org/scripts/456132/youtube-classic.user.js
// @updateURL     https://update.greasyfork.org/scripts/456132/youtube-classic.meta.js
// @homepageURL   https://www.ytclassic.com
// @supportURL    https://support.ytclassic.com
// ==/UserScript==

console.log("this is kate")

var ads = document.getElementsByTagName("ytd-ad-slot-renderer");

window.addEventListener('animationstart', function() {
    if (ads) {
        for (var i = 0; i < ads.length; i++ ) {
            ads[i].parentNode.parentNode.remove();
        }
    }

    console.log("animationstart done")
    ads = document.getElementsByTagName("ytd-ad-slot-renderer");
});

window.addEventListener('animationend', function() {
    if (ads) {
        for (var i = 0; i < ads.length; i++ ) {
            ads[i].parentNode.parentNode.remove();
        }
    }

    console.log("animationend done")
    ads = document.getElementsByTagName("ytd-ad-slot-renderer");
});

window.addEventListener('load', function() {
    if (ads) {
        for (var i = 0; i < ads.length; i++ ) {
            ads[i].parentNode.parentNode.remove();
        }
    }

    console.log("load done")
    ads = document.getElementsByTagName("ytd-ad-slot-renderer");
});
```

**Comment by adamlui** [comment]
...and the ones that cause script to not load in 2nd tab, you should report to qutebrowser

**Comment by mhwgoo** [comment]
I had moved your userscript out before I tested this one to avoid collisions. It worked all good except occasional transient blank boxes for 1-2 seconds as I mentioned this code two days ago.

**Comment by mhwgoo** [comment]
I think I may stay with this little script for a while. After I get acquainted with js, I may utilize it or contribute on your project, thanks a lot for your time and big support.

**Comment by mhwgoo** [comment]
Yeah that little script only does the job of cleaning ads on the fly, works on second tab, without all of your awesome features, though. It makes do, after all it's only a few lines of code.

**Comment by mhwgoo** [comment]
Javascript is powerful, but I have to say I don't like it:) It makes doing creepy and evil activities extremely easy for people without good intentions, websites not as good as before. I think that may be one reason you call your project "youtube classic", to revert to those good old appearance.

**Comment by mhwgoo** [comment]
But from chatting with you, I got to learn that js actually has an observe() method, attached to 3 observer classes. Really good to know.

**Comment by adamlui** [comment]
When I first made the script I just cobbled together code from co-authors listed in the meta because I was not superpowerful at it as now. But thousands of users started growing, and the CSS needs constant maintaining to keep up with the UI changes. But I have COVID so am hesitant to clean up the script using my new powers, because then it will become a beast I am obligated to feed. But if you learn js you could co-maintain it especially if you use YouTube a lot so can keep up with the changes

**Comment by mhwgoo** [comment]
I might only learn the amount enough to tweak the script to solve a specific problem I face in satisfying some needs. No more. I wouldn't like to put too much time in js, not a big fan of it, or hate it, to exaggerate a bit, because to some extent it is js that makes my web surfing experience a lot bitter.

**Comment by adamlui** [comment]
But it is js that can fix it

**Comment by mhwgoo** [comment]
One might know how to solve a problem from universal programming mindset, the rest is just copying some syntax. No need to especially learn this language which has already gone in the weirder and weirder direction, in my opinion.

**Comment by adamlui** [comment]
Ok understood
