### ISSUE TITLE
Closing Chats?

### ISSUE THREAD

**Issue by Tripp1e** [adamlui/userscripts#11]
Everything works fine, but when I go to chat.openai.net, there are like 10 trillion different chats open. Is there a way to make them automatically close?

**Comment by adamlui** [comment]
@Tripp1e Check this script out https://github.com/adamlui/userscripts/tree/master/chatgpt/autoclear-chatgpt-history (I added you as co-author)

**Comment by Tripp1e** [comment]
Nice, Thanks!
