### ISSUE TITLE
autoclear-chatgpt-history.user Can add a button to manually clear instead of automatically clear ? or provide a setting option for users to choose

### ISSUE THREAD

**Issue by XiaoYingYo** [adamlui/userscripts#12]
autoclear-chatgpt-history.user Can add a button to manually clear instead of automatically clear ? or provide a setting option for users to choose

@adamlui

**Comment by adamlui** [comment]
@759852125 I added a toggle

![image](https://user-images.githubusercontent.com/10906554/222903623-a5f647bf-f6d4-4b65-bf88-ea7ca8b6e6ba.png)

If it is disabled, you can click 'Clear conversations' manually

![image](https://user-images.githubusercontent.com/10906554/222903668-4026ec94-d172-4d37-bab9-d7e183ba130f.png)

Can you click update @ https://greasyfork.org/en/scripts/460805 and check it out?
