### ISSUE TITLE
Problems with text or icons make this layout unreasonable, and it should not wrap lines

### ISSUE THREAD

**Issue by XiaoYingYo** [adamlui/userscripts#19]
![image](https://user-images.githubusercontent.com/54934866/223353219-4b0c78e0-25ee-4028-8921-62ed3ffc824e.png)

@adamlui

**Comment by adamlui** [comment]
Hey is this in Violentmonkey and what browser? Also what is your screen resolution?

**Comment by XiaoYingYo** [comment]
> Hey is this in Violentmonkey and what browser? Also what is your screen resolution?

YES,2560 × 1440

**Comment by adamlui** [comment]
> > Hey is this in Violentmonkey and what browser? Also what is your screen resolution?
> 
> YES,2560 × 1440,Chrome 110

I will work on it after I finish the improved ChatGPT Width Pro (I'll tag you in another issue for more info)

**Comment by XiaoYingYo** [comment]
> > > Hey is this in Violentmonkey and what browser? Also what is your screen resolution?
> > 
> > 
> > YES,2560 × 1440,Chrome 110
> 
> I will work on it after I finish the improved ChatGPT Width Pro (I'll tag you in another issue for more info)

Great
