### ISSUE TITLE
Autopass CloudFlare CATCHA gets stuck on iOS with ChatGPT

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [adamlui/userscripts#24]
Exactly what it says in the title; I'm only able to verify by turning off the script and doing it manually. It may need to be tweaked to work better with iOS.

**Comment by adamlui** [comment]
> Exactly what it says in the title; I'm only able to verify by turning off the script and doing it manually. It may need to be tweaked to work better with iOS.

@XiaoYingYo is the author, I don't know if she has an idevice but I don't so cannot fix :(

**Comment by XiaoYingYo** [comment]
This stumps me, because I don't have an IOS phone for debugging

@Amaroq-Clearwater

**Comment by adamlui** [comment]
I believe it has to do with cross origin restrictions for safari as a similar issue occurred in #10

**Comment by adamlui** [comment]
(cloudflare.com embedded in openai.com)
