### ISSUE TITLE
Separate the wide screen and full screen feature

### ISSUE THREAD

**Issue by mefengl** [adamlui/userscripts#26]
The wide-screen mode will always be on when open full-screen mode is on.

**Comment by adamlui** [comment]
Yes I did that intentionally to make it as big as possible, you think it's better without this feature?

**Comment by mefengl** [comment]
If someone needs a widescreen, they can turn it on with a wide-screen button.

Full-screen mode is like something that hides the side menu from me.

If full-screen also makes the content wide, the wide button becomes useless in full-screen mode.

**Comment by adamlui** [comment]
@mefengl check it out I added an option (disabled by default):

![image](https://user-images.githubusercontent.com/10906554/225535062-765d1645-f7e3-4d43-bd76-0c908c2650d2.png)

When it is enabled, full-window will also auto-expand wide screen. When disabled, it will behave exactly how you liked it

**Comment by adamlui** [comment]
> If full-screen also makes the content wide, the wide button becomes useless in full-screen mode.

But it's still useful when full-screen is off, so the menu caters to users like me who want that option when not full-screen, but always want it on in full-screen (to save from 2 clicks)

**Comment by adamlui** [comment]
(The reason I like full-window w/ wide screen is that's how YouTube behaves when clicking full screen)

**Comment by adamlui** [comment]
..but previously disabling full-window left wide-screen on even if never manually activated, now if you enable 'Fuller Window,' if wide screen is off, if you enter/exit full-screen, wide screen will turn on/off (try it out you might like it that way too)

**Comment by mefengl** [comment]
works fine for me, so I will close this issue 🎉
