### ISSUE TITLE
In widescreen mode, you cannot click on `Re-Edit` on the right and `Toggle History Edit` on the left

### ISSUE THREAD

**Issue by XiaoYingYo** [adamlui/userscripts#27]
@adamlui 
In widescreen mode, you cannot click on `Re-Edit` on the right and `Toggle History Edit` on the left

video link:
[https://drive.google.com/file/d/1pOz1NFMJ3aR8XgfS6JasH801kl6kc9HS/view?usp=share_link](https://drive.google.com/file/d/1pOz1NFMJ3aR8XgfS6JasH801kl6kc9HS/view?usp=share_link)

**Comment by adamlui** [comment]
Hey @XiaoYingYo I fixed it

**Comment by XiaoYingYo** [comment]
this is great

**Comment by XiaoYingYo** [comment]
@adamlui 
The switch topic on the left is still unclickable, it is covered, if you haven't noticed, please watch my video again, and pay attention to the position of my mouse pointer

**Comment by adamlui** [comment]
@XiaoYingYo it's probably the script that made the bars smaller causing conflict, what is the name of that so I can test it out

**Comment by XiaoYingYo** [comment]
Even using the `widescreen` script alone still has this problem, and what name are you referring to?

@adamlui

**Comment by XiaoYingYo** [comment]
I have processed

**Comment by adamlui** [comment]
> I have processed

wdym?
