### ISSUE TITLE
Some things are not working and have disappeared 

### ISSUE THREAD

**Issue by Mark242Lenny** [adamlui/userscripts#29]
For the old youtube theme: The subscribe button has shrunk down to like 2 pixels and the subscribe text is also gone. The topbar in youtube when you are watching a video is not present unless you scroll down but it should be completely solid when you are scrolled to the top. Also, the search bar is rounded which there is a style to revert this but it's worth pointing out. Hopefully, these bugs can be fixed. Thanks.

**Comment by adamlui** [comment]
@Mark242Lenny I restored the modern sub button until I re-style it manually to classic one. For the topbar, what's your browser & userscript manager and can you show a screenshot?  For search bar it's square now, can you udpate @ https://greasyfork.org/en/scripts/456132-youtube-classic-remove-rounded-design-return-youtube-dislikes

**Comment by Mark242Lenny** [comment]
i use tamper monkey and here is a screenshot of the top bar not being there (on a video):  
![Annotation 2023-03-25 202619](https://user-images.githubusercontent.com/119706009/227748693-222cedb8-7198-49f7-925b-aae30a9c7e38.png)
And here is what it used to look like 
![image](https://user-images.githubusercontent.com/119706009/227748731-6d2a7916-551d-41c4-8ff1-512ba5e4ccb9.png)

**Comment by adamlui** [comment]
Hey I can't tell what is missing, I see a top bar in all three shots, also can you update to the latest version @ https://ytclassic.com first (it tweaks the search bar and restores missing sub button)

**Comment by Mark242Lenny** [comment]
So basically it's the grey topbar that used to be on the old youtube but they changed something to remove it. The first image shows the top bar being removed recently. The second image is from a while ago  when the top bar was still present, and the third image just shows when you scroll down it shows up again (like it should) For some reason this bug only happens on dark mode because in light mode the white topbar is still there

**Comment by adamlui** [comment]
I can't see anything missing in your screenshots, maybe you can record it using https://ispring-free-cam.en.softonic.com/ and drag and drop it into a reply? (Also try zooming in so your browser with ctrl +/wheelup so the change is more noticable)

**Comment by Mark242Lenny** [comment]
I zoomed it in more as u can see there is no top bar 
![image](https://user-images.githubusercontent.com/119706009/227749884-1f82dcd5-be4e-4b1e-a3f9-7b3973e5c282.png)
and here is what happens when i scrolled down a little
![image](https://user-images.githubusercontent.com/119706009/227749913-064bcdcf-b5e1-42d0-a71e-d7e6c27d00af.png)
there should be a top bar without having to scroll down. It actually appears for a split second while the page is loading: 
![image](https://user-images.githubusercontent.com/119706009/227749953-2eb78621-3ff6-40a6-a569-c7d0cc26210e.png)
but once the page loads the grey bar vanishes like in the first image.

**Comment by Mark242Lenny** [comment]
do you see the grey bar its more zoomed in its like a lighter grey than the dark grey background

**Comment by adamlui** [comment]
No  I don't :/

**Comment by Mark242Lenny** [comment]
Try turning your brightness up because i can see it. Look at the bottom one. see where all the loading icons are and the search bar and the 3 lines. all of that is docked inside a grey bar. But when the page loads that grey bar goes invisible like in the first image there is no grey bar docking the search bar the menu icon and the other icons at the top.

**Comment by Mark242Lenny** [comment]
When i go into theater mode the grey bar is still at the top of the screen but when im not in theater mode its not at the top of the screen anymore and its just the background. Here is what it looked like in theater mode 
![image](https://user-images.githubusercontent.com/119706009/227780714-76de6c88-aaeb-4444-aa64-4f7f0a4d949d.png)

**Comment by Mark242Lenny** [comment]
you can put the first and last image from before into an RGB picker if that would help too. I really don't know how or why youtube would change something like that. It looks ugly not having a topbar to doc all the icons when you watching videos (outside of theater mode) Maybe they removed it because of ambient mode but this script actually used to add the topbar back in the past but youtube changed something and now it doesn't (when you are out of theater mode and watching any video)

**Comment by adamlui** [comment]
I believe you but I can't see the dock you're talking about so can't fix it. My monitor is very old the brightness won't go up

**Comment by Mark242Lenny** [comment]
ok can you try using an rgb picker on this image (without the doc): 
![image](https://user-images.githubusercontent.com/119706009/227782545-3f987dec-b95d-4af0-b014-2ce79723b11e.png)
And this image (with the doc): 
![image](https://user-images.githubusercontent.com/119706009/227782576-cc98cea1-191e-4c49-b558-af45870ae823.png)
The doc shows while the page is loading but once the page loads it disappears. it might have something to do with when you scroll down the transparency of the doc changes. and maybe youtube changed something with the padding or something. Put  it in an rgb picker and you will see the difference with the doc and without. the one without the doc will have the same rgb value if you click where the doc used to be and if you click on the background where the doc isnt. But on the second image where the page was still loading and the doc was present you will get 2 different rgb values.

**Comment by adamlui** [comment]
I was up all night coding but I will examine it closer to try to fix soon

**Comment by adamlui** [comment]
On another day I mean

**Comment by Mark242Lenny** [comment]
Ok, Thanks :)

**Comment by Mark242Lenny** [comment]
I found the issue with the top bar! the opacity is been overridden by an element style that makes it set to 0. If you add an !important to the opacity 1 in the element it should fix the issue. Whenever you have a chance to fix it 
![image](https://user-images.githubusercontent.com/119706009/229287215-a38dc0f5-92ad-4a4e-aa7e-2001cabf6fe7.png)

**Comment by Mark242Lenny** [comment]
add this into the style sheet part of the code 
#background.ytd-masthead{opacity: 1!important;}

**Comment by adamlui** [comment]
@Mark242Lenny can you try to edit your userscript with this fix and see if it works (because I can't tell on my monitor and w/ my poor vision)? Then if it does, can you edit the user.js here, which will create a branch you can submit as pull request then you become contributor

**Comment by adamlui** [comment]
@Mark242Lenny or I can add the !important and update the code, either way let me know (but I won't know if it worked it will be a mystery until your reveal)

**Comment by Mark242Lenny** [comment]
I edited my script so it is fixed all I did was add that line of code into the styling part of the script where all they styles appended to YouTube
