### ISSUE TITLE
it keeps loading and does not load, I installed some other things that it asked for but it did not

### ISSUE THREAD

**Issue by Sandy9843** [adamlui/userscripts#30]
it keeps loading and does not load, I installed some other things that it asked for but it did not

**Comment by adamlui** [comment]
Hi @Sandy9843 which script and browser, and are you using Tampermonkey or Violentmonkey?

**Comment by adamlui** [comment]
@Sandy9843 if you mean BraveGPT, can you remove the old installation (I forgot to add an auto-update meta) and install the new version: https://greasyfork.org/en/scripts/462440-bravegpt

This version will load (and not require you have an OpenAI account) also will auto-update for future improvements

**Comment by Nord1cWarr1or** [comment]
> it keeps loading and does not load

Same for me. I have Tampermonkey v4.18.1 and FireDragon browser.  (a fork of FireFox)

**Comment by adamlui** [comment]
@Nord1cWarr1or did you try to install the new version @ https://greasyfork.org/en/scripts/462440-bravegpt ? (It is updated to use a network of API's and retry if one fails) Or do you refer to a different script?

**Comment by Nord1cWarr1or** [comment]
@adamlui Sorry, I forgot to point that out. I tried to use DuckDuckGPT

**Comment by adamlui** [comment]
@Nord1cWarr1or Ohhh can you check back in a day? I will get it to work (but I want to preserve streaming support is why it takes so long)

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or Ohhh can you check back in a day? I will get it to work (but I want to preserve streaming support is why it takes so long)

Sure, I can help with tests.

**Comment by Sandy9843** [comment]
I'm using Tampermonkey, ok,

**Comment by adamlui** [comment]
@Sandy9843 
> I'm using Tampermonkey, ok,

Hey are you using BraveGPT? If so, can you visit https://greasyfork.org/en/scripts/462440-bravegpt and click Update? It will load now!

![image](https://user-images.githubusercontent.com/10906554/228687086-323ede15-0dad-497a-ac9e-9fbdcf243498.png)

If you are using DuckDuckGPT, can you wait until later, it will also work (no need to click update)

**Comment by Nord1cWarr1or** [comment]
@adamlui Hi! I tested the update today, but unfortunately it's still the same. "Waiting for ChatGPT response..."
To rule out third-party factors, I also tried this:
- Disable uBlock on the DuckDuckGo page.
- Another browser (Ungoogled chromium)
- Using VPN
- Violentmonkey instead of Tampermonkey

**Comment by adamlui** [comment]
Hey @Nord1cWarr1or is line 3:

```js
// @version             2023.03.30.1
```

...and when you click Tampermonkey, is there a green checkmark visible next to **Proxy API Mode**:

![image](https://user-images.githubusercontent.com/10906554/229268938-83a91825-2e93-429e-91e7-c65ccbc2fe24.png)

**Comment by Nord1cWarr1or** [comment]
> ...and when you click Tampermonkey, is there a green checkmark visible next to **Proxy API Mode**:

Yep
![image](https://user-images.githubusercontent.com/47604048/229269844-02ec9717-d408-4d12-a852-6bcb5f5e66da.png)

**Comment by adamlui** [comment]
@Nord1cWarr1or  Can you press Ctrl+Shift+I and copy/paste any errors that appear in the console

**Comment by adamlui** [comment]
Also are you in Russia? I noticed it is restricted there: 
![image](https://user-images.githubusercontent.com/10906554/229270227-adf3053b-2b84-4202-abd7-3f3096f5dbeb.png)

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or Can you press Ctrl+Shift+I and copy/paste any errors that appear in the console
```
🐤 DuckDuckGPT >> Error calling https://api.pawan.krd/v1/chat/completions. Trying another endpoint... [DuckDuckGPT 🤖.user.js:169:39](moz-extension://3002f8f3-bc11-434c-b31e-06d96c22d250/userscripts/DuckDuckGPT%20%F0%9F%A4%96.user.js?id=9d72a38a-8af2-4ecc-b3ad-787fa1d2263f)
🐤 DuckDuckGPT >> Endpoint used: undefined [DuckDuckGPT 🤖.user.js:168:38](moz-extension://3002f8f3-bc11-434c-b31e-06d96c22d250/userscripts/DuckDuckGPT%20%F0%9F%A4%96.user.js?id=9d72a38a-8af2-4ecc-b3ad-787fa1d2263f)
injected: Refused to connect to "undefined": Blocked by @connect CORS check [content.js:8:1224](moz-extension://3002f8f3-bc11-434c-b31e-06d96c22d250/content.js)
Uncaught TypeError: can't convert msg to primitive type
    error moz-extension://3002f8f3-bc11-434c-b31e-06d96c22d250/userscripts/DuckDuckGPT 🤖.user.js?id=9d72a38a-8af2-4ecc-b3ad-787fa1d2263f:169
    onerror moz-extension://3002f8f3-bc11-434c-b31e-06d96c22d250/userscripts/DuckDuckGPT 🤖.user.js?id=9d72a38a-8af2-4ecc-b3ad-787fa1d2263f:266
    St https://duckduckgo.com/?t=ffab&q=LD_LIBRARY_PATH&ia=web:9
    onerror https://duckduckgo.com/?t=ffab&q=LD_LIBRARY_PATH&ia=web:25
    St https://duckduckgo.com/?t=ffab&q=LD_LIBRARY_PATH&ia=web:9
    i https://duckduckgo.com/?t=ffab&q=LD_LIBRARY_PATH&ia=web:34
    St https://duckduckgo.com/?t=ffab&q=LD_LIBRARY_PATH&ia=web:9
    r https://duckduckgo.com/?t=ffab&q=LD_LIBRARY_PATH&ia=web:22
    Fo https://duckduckgo.com/?t=ffab&q=LD_LIBRARY_PATH&ia=web:23
    g https://duckduckgo.com/?t=ffab&q=LD_LIBRARY_PATH&ia=web:67
    g https://duckduckgo.com/?t=ffab&q=LD_LIBRARY_PATH&ia=web:67
[eval:169:31](chrome://devtools/content/webconsole/eval)
uncaught exception: Object```

**Comment by Nord1cWarr1or** [comment]
> Also are you in Russia? I noticed it is restricted there: ![image](https://user-images.githubusercontent.com/10906554/229270227-adf3053b-2b84-4202-abd7-3f3096f5dbeb.png)

Yes, but I can use it via VPN or API.
And I have already tried turning on the VPN for DuckDuckGO

**Comment by adamlui** [comment]
@Nord1cWarr1or can you update by clicking https://greasyfork.org/scripts/459849-duckduckgpt/code/DuckDuckGPT%20%F0%9F%A4%96.user.js and paste the errors again (this time it will be more detailed)

**Comment by Nord1cWarr1or** [comment]
@adamlui
`DuckDuckGPT >> ERROR: Event status: 400 [DuckDuckGPT 🤖.user.js:169:39](moz-extension://3002f8f3-bc11-434c-b31e-06d96c22d250/userscripts/DuckDuckGPT%20%F0%9F%A4%96.user.js?id=9d72a38a-8af2-4ecc-b3ad-787fa1d2263f)
🐤 DuckDuckGPT >> ERROR: Event response: {"status":false,"error":"Your API key is not allowed to be used from this IP address, if you want to reset your authorized IP address please use /resetip on our discord server","hint":"You can get support from https://discord.pawan.krd/","info":"https://gist.github.com/PawanOsman/72dddd0a12e5829da664a43fc9b9cf9a","support":"https://discord.pawan.krd/"}`

**Comment by adamlui** [comment]
That was really helpful now I have to figure out how to mask the IP

**Comment by adamlui** [comment]
@Nord1cWarr1or I think I did it, can you test out new version https://greasyfork.org/scripts/459849-duckduckgpt/code/DuckDuckGPT%20%F0%9F%A4%96.user.js

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or I think I did it, can you test out new version https://greasyfork.org/scripts/459849-duckduckgpt/code/DuckDuckGPT%20%F0%9F%A4%96.user.js

Yes! It seems to be working now. Thank you.

**Comment by adamlui** [comment]
@Nord1cWarr1or you're welcome, can u give this repo a ⭐ if you wanna help me out: https://github.com/kudoai/duckduckgpt
