### ISSUE TITLE
[Enhancement] Code readability

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [adamlui/userscripts#4]
I think it would be a good idea to use new lines in your code to break it up a bit which would make it more readable, and to add a lot more comment lines to make it more understandable. I started learning JavaScript recently, but the code in [the main script file](https://github.com/adamlui/userscripts/blob/master/youtube-classic.user.js) is hard to read and understand.

**Comment by adamlui** [comment]
OK I will try to do that moving forward, also thanks for mentioning librewolf, I had been looking for a more private browser not based on chromium! Also check out https://github.com/adamlui/userscripts/discussions/3 I added the YT Shorts redirect

**Comment by adamlui** [comment]
Hey @ae5960e8-a6fc-491f-b252-898ecf59af95 I listened to you, check out the latest update with detailed comments:

![image](https://user-images.githubusercontent.com/10906554/215316704-4149c4b1-a77c-41cf-a048-dd393d9ef161.png)
