### ISSUE TITLE
PikPak Enhance vulnerability

### ISSUE THREAD

**Issue by adamlui** [adamlui/userscripts#44]
@XiaoYingYo snyk reported a vulnerability in PikPak Enhance:

![image](https://github.com/adamlui/userscripts/assets/10906554/60b55d07-5287-415c-a461-fa83df5ee1d0)

**Comment by adamlui** [comment]
@XiaoYingYo here's their fix analysis:

Best practices for prevention:

- Plan software architecture such that keys and passwords are always stored outside the code, wherever possible.
- Plan encryption into software architecture for all credential information and ensure proper handling of keys, credentials, and passwords.
- Prompt for a secure password on first login rather than hard-code a default password.
- If a hardcoded password or credential must be used, limit its use, for example, to system console users rather than via the network.
- Use strong hashes for inbound password authentication, ideally with randomly assigned salts to increase the difficulty level in case of brute-force attack.

<br>

预防的最佳做法：

- 规划软件架构，尽可能将密钥和密码始终存储在代码之外。
- 为所有凭证信息将加密计划纳入软件架构，并确保正确处理密钥、凭证和密码。
- 首次登录时提示输入安全密码，而不是硬编码默认密码。
- 如果必须使用硬编码密码或凭据，请限制其使用，例如，系统控制台用户而不是通过网络。
- 使用强哈希值进行入站密码身份验证，最好使用随机分配的盐来增加暴力攻击的难度级别。

**Comment by XiaoYingYo** [comment]
OK
