### ISSUE TITLE
chatgpt widescreen not working unfortuantely

### ISSUE THREAD

**Issue by Wladefant** [adamlui/userscripts#60]
nice idea, unfortunately not working anymore 
![image](https://github.com/adamlui/userscripts/assets/79611093/e167dd5b-1dcb-4b25-8a9b-10db14c550e9)

**Comment by Wladefant** [comment]
Yes Plus Subscriber using edge, tried adguard and also the extension

**Comment by Wladefant** [comment]
On another note, somehow none of your scripts work with adguard.

**Comment by adamlui** [comment]
@Wladefant were you using the extension from the Microsoft store? If so they just approved an update I wrote a long time ago (their process is really slow) can you check if it works now? https://edge.chatgptwidescreen.com

**Comment by Wladefant** [comment]
Yeah works perfectly thanks
