### ISSUE TITLE
github-star-history: Failed to fetch image

### ISSUE THREAD

**Issue by jesus2099** [adamlui/userscripts#74]
I am running the script with Vivaldi 6.6.3271.57 (Stable channel) (64-bit) and Violentmonkey 2.18.0.

This code:

https://github.com/adamlui/userscripts/blob/706ce0da524a7ac9183bbab23b7fcb1ffb5febc5/github/github-star-history/github-star-history.user.js#L385-L387

Although the `imgURL` contains a valid image URL that is loading good, manually,
This code always prints `>> Failed to fetch image` in the console.
I don't know how `await GM.xmlHttpRequest` works, but it could be the cause.

**Comment by adamlui** [comment]
Hey @jesus2099 thansk for reporting the issue, I find that many functions that work in Tampermonkey consistenly fail in Violentmonkey. I'm goign to open an issue in that repo to see if they can fix it

**Comment by adamlui** [comment]
@jesus2099 it's fixed if you update to 2024.4.9 @ https://greasyfork.org/en/scripts/473377-github-star-history

**Comment by jesus2099** [comment]
Super! 
For info, it works on Android 9 Kiwi Browser 124.0.6327.2 Violentmonkey 2.18.0
